In [1]:
#imports
import pandas as pd
import csv
import time

In [2]:
import requests

def make_get_request(url):
    try:
        response = requests.get(url)

        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            return response.text  # If you expect JSON data, use response.json() instead of response.text
        else:
            print(f"Request failed with status code: {response.status_code}")
            return None

    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return None

# Example usage:
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT6HrGh7EOzzejrvzkG_TGUM_GoGVDuvlUq7UcYqHlESZX6Vv8Hvwatsp4FLdE4Nmff9z5LSG3KQFq9/pub?gid=700061257&single=true&output=csv"
data = make_get_request(url)
li=[]
if data:
    # print(data)
    li.append(data)

print(li[0])

Operators,Machine,Job
Sukhpreet,M/C No. 2,S.R. Shaft THD
Babita,M/C No. 3,
Lalita,M/C No. 4,S.R. Shaft DRIL
Rakhi,M/C No. 5,S.R. Shaft 1st  Operator
Sonia,M/C No. 6,ALU. BUSH FINAL
Vinod,M/C No. 7,ALU. BUSH ROUGH
Diyansh,M/C No. 8,
Som,M/C No. 9,
Shiva,M/C No. 10,ALU. BUSH FINAL
Sanjay,M/C No. 11,ALU. BUSH ROUGH
Harpreet,VMC Big,
Karan,VMC Small,
Mohit,GRD M/C,
Pintu,CNC GRD,
Sangam,,
Anil,,
Ram Kishor,,
Pawan,,
Ruby,,

In [3]:
prdf=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT6HrGh7EOzzejrvzkG_TGUM_GoGVDuvlUq7UcYqHlESZX6Vv8Hvwatsp4FLdE4Nmff9z5LSG3KQFq9/pub?gid=700061257&single=true&output=csv")

In [4]:
prdf

     Operators     Machine                       Job
0    Sukhpreet   M/C No. 2            S.R. Shaft THD
1       Babita   M/C No. 3                       NaN
2       Lalita   M/C No. 4           S.R. Shaft DRIL
3        Rakhi   M/C No. 5  S.R. Shaft 1st  Operator
4        Sonia   M/C No. 6           ALU. BUSH FINAL
5        Vinod   M/C No. 7           ALU. BUSH ROUGH
6      Diyansh   M/C No. 8                       NaN
7          Som   M/C No. 9                       NaN
8        Shiva  M/C No. 10           ALU. BUSH FINAL
9       Sanjay  M/C No. 11           ALU. BUSH ROUGH
10    Harpreet     VMC Big                       NaN
11       Karan   VMC Small                       NaN
12       Mohit     GRD M/C                       NaN
13       Pintu     CNC GRD                       NaN
14      Sangam         NaN                       NaN
15        Anil         NaN                       NaN
16  Ram Kishor         NaN                       NaN
17       Pawan         NaN                       NaN
18        Ruby         NaN                       NaN

In [9]:
# oprdf=prdf['Operators'].values
# oprlist=list(oprdf)
# machdf=prdf['Machine'].values
# machlist=list(machdf)
jobdf=prdf['Job']
jobdf.dropna(inplace=True)
joblist=list(jobdf)

In [10]:
joblist

['S.R. Shaft THD',
 'S.R. Shaft DRIL',
 'S.R. Shaft 1st  Operator',
 'ALU. BUSH FINAL',
 'ALU. BUSH ROUGH',
 'ALU. BUSH FINAL',
 'ALU. BUSH ROUGH']

In [ ]:
prdf=pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT6HrGh7EOzzejrvzkG_TGUM_GoGVDuvlUq7UcYqHlESZX6Vv8Hvwatsp4FLdE4Nmff9z5LSG3KQFq9/pub?gid=700061257&single=true&output=csv")
jobdf=prdf['Job']
jobdf.dropna(inplace=True)
joblist=list(jobdf)